name: Discord
on:

    - push
    
permissions:
  contents: read
jobs: 

discord_test_message:
    runs-on: ubuntu-latest
    name: Discord Commits
    steps:
       -name: Checkout
        uses: actions/checkout@v4

       -name: Send message to discord   
        uses: ./
        with:
            webhook: ${{ secrets.DISCORD_WEBHOOK }}
            template: "avatar-with-link"
            include-extras: true   
