name: Run FastAPI Tests

on:
  pull_request:
    branches:
      - main
permissions:   
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest
          pip install httpx
      - name: Run tests
        run: pytest
